// Code generated by logcopter-gen; DO NOT EDIT.

package jsbridge

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.go-go-gepa.pkg.jsbridge")
